Repository NETWAYS/support-collector, pull requests merged in 2024-11, with the labels that each got.

#136 Update obfuscation
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  Makefile
  README.md
  go.mod
  internal/collection/collection.go
  internal/obfuscate/obfuscate.go
  internal/obfuscate/obfuscate_test.go
  internal/util/testing.go
  internal/util/util.go
  main.go
  modules/base/kernel.go
  modules/icinga2/api.go
  modules/icinga2/collector.go
Labels: bug, documentation

#139 Fix wizard dependency for icinga2
  main.go
Labels: bug

#140 Respect whitespaces in wizard StringSliceVar
  internal/config/wizard.go
Labels: bug

#144 Obfuscate icingadb.yml passwords
  modules/icingadb/collector.go
Labels: bug

#145 Remove obsolete code
  modules/icinga2/api.go
Labels: quality

#142 Add obfuscators to wizard
  internal/config/wizard.go
  main.go
Labels: feature

#146 fetch system overcommit_memory
  modules/icingadb/collector.go
  modules/redis/collector.go
Labels: feature
